version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    # executor: docker/docker
    docker:
      - image: cimg/base:stable
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    environment:
      DOCKER_USER: ${DOCKER_USERNAME}
      DOCKER_PASS: ${DOCKER_PASSWORD}
      UID: ${UID}
      GID: ${GID}
      USER: ${USER}
    steps:
      - checkout
      - docker/build:
          dockerfile: Dockerfile
          tag: ${CIRCLE_SHA1}
          image: dermsythn3d
      - docker/push:
          image: '${DOCKER_USER}/dermsynth3d'

workflows:
  build-and-push:
    jobs:
      - build:
          context:
            - build-env-vars
            - docker-hub-creds