version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
        auth: 
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          # image: dermsynth3d/v1
          image: sinashish/dermsynth3d
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sinashish/dermsynth3d
      # - docker/publish:
      #     deploy: true
      #     image: dermsynth3d/v1
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push
