name: Build and Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: git submodules
      uses: snickerbockers/submodules-init@v4
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file dermsynth3d.yml --name base
        pip install -r requirements.txt
        # $CONDA/bin/conda activate 
    - name: Check torch versions
      run: |
        $CONDA/bin/conda list | grep torch
        # pip freeze | grep torch\|cv\|sci
      shell: bash
    - name: Test Imports
      run: |
        python -u scripts/gen_data.py 
      shell: bash 
    - name: Lint with Black
      uses: psf/black@stable
      with: 
        options: "--check --verbose"
        jupyter: true
